version: "3.7"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - sword-health-mysql-data:/var/lib/mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  app:
    depends_on:
      - mysql
    build: ./app
    working_dir: /app
    volumes:
      - ./:/app
    restart: unless-stopped
    command: sh -c "yarn install && yarn start"
    env_file: ./.env
    environment:
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DB: $MYSQLDB_DATABASE
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - $RABBITMQ_LOCAL_PORT:$RABBITMQ_DOCKER_PORT
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  sword-health-mysql-data:
  rabbitmq_data:
